# Generated by Django 5.0.6 on 2024-06-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="project_images/"),
        ),
    ]
